name: Upload Python Package

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0

env:
  PIP_ROOT_USER_ACTION: ignore
  EARTHENGINE_SERVICE_ACCOUNT: ${{ secrets.EARTHENGINE_SERVICE_ACCOUNT }}
  EARTHENGINE_PROJECT: ${{ secrets.EARTHENGINE_PROJECT }}

jobs:
  tests:
    uses: ./.github/workflows/unit.yaml
    secrets:
      EARTHENGINE_SERVICE_ACCOUNT: ${{ secrets.EARTHENGINE_SERVICE_ACCOUNT }}
      EARTHENGINE_PROJECT: ${{ secrets.EARTHENGINE_PROJECT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install build nox[uv]
      - name: update citation date
        run: nox -s release-date
      - name: Build package
        run: python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
